hosts=[
        'ambrogio.cs.unibo.it',         'manrico.cs.unibo.it',
        'grenvil.cs.unibo.it',          'annina.cs.unibo.it',
        'pancrazio.cs.unibo.it',        'hansel.cs.unibo.it',
        'ruiz.cs.unibo.it',             'filindo.cs.unibo.it',
        'margherita.cs.unibo.it',       'lily.cs.unibo.it',
        'rosina.cs.unibo.it',           'donbartolo.cs.unibo.it',
        'ferrando.cs.unibo.it',         'fidelia.cs.unibo.it',
        'elisabetta.cs.unibo.it',       'aremberg.cs.unibo.it',
        'edgar.cs.unibo.it',            'tebaldo.cs.unibo.it',
        'doncarlo.cs.unibo.it',         'malatesta.cs.unibo.it',
        'eufemia.cs.unibo.it',          'ernesto.cs.unibo.it',
        'odoardo.cs.unibo.it',          'norina.cs.unibo.it',
        'dorina.cs.unibo.it',           'amneris.cs.unibo.it',
        'tigrana.cs.unibo.it',          'donpasquale.cs.unibo.it',
        'gualtiero.cs.unibo.it',        'donandronico.cs.unibo.it',
        'bettina.cs.unibo.it',          'azucena.cs.unibo.it',
        'frank.cs.unibo.it',            'gretel.cs.unibo.it',
        'milada.cs.unibo.it',           'doncalascione.cs.unibo.it',
        'moschina.cs.unibo.it',         'benes.cs.unibo.it',
        'brander.cs.unibo.it',
];
hosts_boh=[
	'abdallo.cs.unibo.it',		'abigaille.cs.unibo.it',	
	'alcindoro.cs.unibo.it',	'altoum.cs.unibo.it',
	'amonasro.cs.unibo.it',		'annie.cs.unibo.it',
	'antonio.cs.unibo.it',		'bess.cs.unibo.it',
	'brangania.cs.unibo.it',	'calaf.cs.unibo.it',
	'cassio.cs.unibo.it',		
	'cherubino.cs.unibo.it',	'clara.cs.unibo.it',
	'crown.cs.unibo.it',		'dancairo.cs.unibo.it',
	'donbasilio.cs.unibo.it',	'doncurzio.cs.unibo.it',
	'edmondo.cs.unibo.it',		'emilia.cs.unibo.it',
	'eva.cs.unibo.it',		'fenena.cs.unibo.it',
                                	
	'geronte.cs.unibo.it',		'giovanna.cs.unibo.it',
	'gisella.cs.unibo.it',		'giuseppe.cs.unibo.it',	
	'ismaele.cs.unibo.it',		'ulrica.cs.unibo.it',
	'jim.cs.unibo.it',		'kurwenal.cs.unibo.it',
	'lescaut.cs.unibo.it',		'lucia.cs.unibo.it',
	'ludovico.cs.unibo.it',		'marcellina.cs.unibo.it',
	'maria.cs.unibo.it',		'marullo.cs.unibo.it',
                        		'mercedes.cs.unibo.it',	
	'mimi.cs.unibo.it',		'montano.cs.unibo.it',	
	'morales.cs.unibo.it',		'musetta.cs.unibo.it',
	'nelson.cs.unibo.it',		
	'peter.cs.unibo.it',		'pinkerton.cs.unibo.it',
	'porgy.cs.unibo.it',		'radames.cs.unibo.it',
        'remarke.cs.unibo.it',	        'remendado.cs.unibo.it',
        'renato.cs.unibo.it',           'robbins.cs.unibo.it',
        'roderigo.cs.unibo.it',
];
