hosts=[
	'abdallo.cs.unibo.it',		'abigaille.cs.unibo.it',	
	'alcindoro.cs.unibo.it',	'altoum.cs.unibo.it',
	'amonasro.cs.unibo.it',		'annie.cs.unibo.it',
	'antonio.cs.unibo.it',		'bess.cs.unibo.it',
	'brangania.cs.unibo.it',	'calaf.cs.unibo.it',
	'cassio.cs.unibo.it',		
	'cherubino.cs.unibo.it',	'clara.cs.unibo.it',
	'crown.cs.unibo.it',		'dancairo.cs.unibo.it',
	'donbasilio.cs.unibo.it',	'doncurzio.cs.unibo.it',
	'edmondo.cs.unibo.it',		'emilia.cs.unibo.it',
	'eva.cs.unibo.it',		'fenena.cs.unibo.it',
                                	
	'geronte.cs.unibo.it',		'giovanna.cs.unibo.it',
	'gisella.cs.unibo.it',		'giuseppe.cs.unibo.it',	
	'ismaele.cs.unibo.it',		'ulrica.cs.unibo.it',
	'jim.cs.unibo.it',		'kurwenal.cs.unibo.it',
	'lescaut.cs.unibo.it',		'lucia.cs.unibo.it',
	'ludovico.cs.unibo.it',		'marcellina.cs.unibo.it',
	'maria.cs.unibo.it',		'marullo.cs.unibo.it',
                        		'mercedes.cs.unibo.it',	
	'mimi.cs.unibo.it',		'montano.cs.unibo.it',	
	'morales.cs.unibo.it',		'musetta.cs.unibo.it',
	'nelson.cs.unibo.it',		
	'peter.cs.unibo.it',		'pinkerton.cs.unibo.it',
	'porgy.cs.unibo.it',		'radames.cs.unibo.it',
        'remarke.cs.unibo.it',	        'remendado.cs.unibo.it',
        'renato.cs.unibo.it',           'robbins.cs.unibo.it',
        'roderigo.cs.unibo.it';
];
